### ISSUE TITLE
Unknown bitmap format 1026

### ISSUE THREAD

**Issue by qoire** [angelsl/ms-reWZ#2]
Hey I know this has been brought up on the MSIT thread but I thought i'd throw it up again to see if theres been any update.

**Comment by angelsl** [comment]
No, I didn't really make any progress and gave up a while ago.

I've lost the sample of the 1026 bitmap I was using too, so I can't try again unless someone can give me a sample.

**Comment by retep998** [comment]
1026 should be https://www.opengl.org/wiki/S3_Texture_Compression

**Comment by qoire** [comment]
Thanks ill have a look!

**Comment by qoire** [comment]
Hi just to close the issue: (Thank you retep998 for the insight)
case 1026 is compressed using Dxt3 format. 
I managed to decompress the image using the squish library.
