### ISSUE TITLE
Blank png file extracted from .wz files

### ISSUE THREAD

**Issue by qoire** [angelsl/ms-reWZ#3]
Hi again, sorry for bothering, 
While extracting the .png files I've encountered a lot of instances where the extracted .png file was blank (no data). I've encountered similar output trying to extract files using maplelib. I was wondering if there was any insight to be learnt about why this is occurring.

Below is the two images I have extracted, from the same animation:
This is the blank .png extract:
![failed](https://cloud.githubusercontent.com/assets/4521292/7766010/c249ceca-0032-11e5-94e9-1a49d420a201.png)

And this is the extract with content:
![passed](https://cloud.githubusercontent.com/assets/4521292/7766020/db889c54-0032-11e5-8edb-b87ee7f1a0eb.png)

The headers with height and width are all formatted correctly, it's just that the data is missing.

I used this .wz file (yes Map.wz is huge now):
https://mega.co.nz/#!tUlCiBaZ!xM-0-cnfmVq82tlN9q8u_3kWJVmdM-ngMKys2gyeEDU

and the paths of the two images being extracted are:
"DynamicObjectStateEffect.img/86301010X/open/hide/4" //blank
"DynamicObjectStateEffect.img/86301010X/open/hide/0" //working

**Comment by angelsl** [comment]
Not a bug.

The images themselves are actually blank.
