### ISSUE TITLE
Sound file header read error

### ISSUE THREAD

**Issue by jeremistadler** [angelsl/ms-reWZ#4]
There seems to be a problem with reading the sound of ```/BgmGL.img/Amorianchallenge```

Crashes with "Arithmetic operation resulted in an overflow." when trying to read a byte array of negative length.

To repoduce: 

```
var xz = new WZFile("Sound.wz", WZVariant.EMS, false);
var soundData = ((WZAudioProperty)xz.MainDirectory["BgmGL.img"]["Amorianchallenge"]).Value;
```

**Comment by angelsl** [comment]
Are you using EMS WZ files? What version?

**Comment by jeremistadler** [comment]
Thanks for looking in to it,

The GuessVersion version variable says 102 so guess the wz file is for v.102.
Using EMS files, [Link to the Sound.wz file I used](http://mapleassets.jeremi.se/sound.wz)

Here's the hack I did to make it work for most mp3's, searches for the mp3 magic bytes. Works on most files but some mp3 outputs looks encrypted.

Btw, here's the project i'm using this for: http://maplestoryweb.github.io/maplestoryweb/

**Comment by angelsl** [comment]
33a2ec339fb8fd328acc72dfa9b82862e6c7f8d2 should fix it. Please verify.

**Comment by jeremistadler** [comment]
Thanks for working on it! 

"BgmGL.img/Amorianchallenge" now works but some songs got padded with zeroes at the start.
One of the now broken ones: "BgmGL.img/011_Mach"

**Comment by angelsl** [comment]
@jeremistadler

Not all sound files are MP3s by the way. Some of them may be raw PCM samples aka raw WAV files with not even a header.

I guess I will expose the GUIDs and WAVEFORMATEX header, as well as do some rudimentary parsing &mdash; full support for that is out of scope for reWZ; proper Windows audio libraries like NAudio will have the functionality to deal with the headers and GUIDs.

**Comment by jeremistadler** [comment]
Ahh! That explains why some files work and some don't :+1:
Please close this issue
