### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by Heasn** [angelsl/ms-reWZ#7]
Hi, angelsl! When I'm trying to read Wz file which was used in **Chinese MapleStory** and I get a **System.AccessViolationException**. The Chinese MapleStory Wz files' aes iv is as seem as **BMS.** Then I'm trying to figure out what had happened to the code. I find it seems the function **ReadWZOffset** in class **"WZBinaryReader"** calc a wrong offset to pointer then the pointer pointed to a wrong address which could be a part of protected memory.

This are my stacktrace:
   

> 在 UsefulThings.PointerStream.ReadByte() 位置 F:\ms-reWZ-master\UsefulThings\PointerStream.cs:行号 75
>    在 reWZ.WZBinaryReader.ReadWZStringBlock(Boolean encrypted) 位置 F:\ms-reWZ-master\WZBinaryReader.cs:行号 131
>    在 reWZ.WZFile.<GuessVersionWithImageOffsetAt>b__19_0() 位置 F:\ms-reWZ-master\WZFile.cs:行号 222
>    在 reWZ.WZBinaryReader.PeekFor[T](Func`1 result) 位置 F:\ms-reWZ-master\WZBinaryReader.cs:行号 87
>    在 reWZ.WZFile.GuessVersionWithImageOffsetAt(Int16 ver, Int64 offset) 位置 F:\ms-reWZ-master\WZFile.cs:行号 222
>    在 reWZ.WZFile.GuessVersion() 位置 F:\ms-reWZ-master\WZFile.cs:行号 93
>    在 reWZ.WZFile.Parse() 位置 F:\ms-reWZ-master\WZFile.cs:行号 84
>    在 reWZ.WZFile..ctor(String path, WZVariant variant, Boolean encrypted, WZReadSelection flag) 位置 F:\ms-reWZ-master\WZFile.cs:行号 59

**Comment by angelsl** [comment]
Can you upload the offending WZ file (or if there are multiple, the smallest one)?

Thank you.

**Comment by Heasn** [comment]
Could you tell me your e-mail address and I will send you a wz file. There are something wrong when I upload the file to GitHub.
BTW, when I use 1.1.6 release version, it won't throw those exceptions.

**Comment by angelsl** [comment]
You can get my email address from the Git commit information.

Alternatively, (and personally I'd prefer this), just upload the file to some file hosting service.

**Comment by Heasn** [comment]
I didn't find your email address but there is download link:
https://mega.nz/#!wZ8CmIjB!dUXO29_vU-txfxZF-GolzUzfqkvWj9c70ib8I7Y5tvg

**Comment by angelsl** [comment]
b4b86aa should fix this, please test. Help me close the issue if it's fixed.

Thank you!
